spring.application.name=short-link-service
spring.profiles.active=postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/short_link

spring.datasource.username=short_link
spring.datasource.password=short_link_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
